### ISSUE TITLE
Find list of music bands

### ISSUE THREAD

**Issue by crudmucosa** [crudmucosa/jojonamegenerator#1]
To populate the list/database/dataset of bands needed to generate the stand names, we need some websites to scrape for the information. Find some good sites to scrape.

**Comment by aieshajohnson** [comment]
- https://www.flavorwire.com/182592/an-alphabetical-list-of-105-90s-alternative-bands-that-still-exist
- https://seatgeek.com/tba/music/best-pop-punk-emo-bands-of-the-late-90s-early-2000s/
- https://www.cheatsheet.com/entertainment/90s-music-best-90s-bands-musicians.html/
- https://www.rockarchive.com/artists
- https://rateyourmusic.com/list/jweber14/top_50_bands_of_the_90s/
