### ISSUE TITLE
Find list of adjectives

### ISSUE THREAD

**Issue by crudmucosa** [crudmucosa/jojonamegenerator#3]
Either find a list of adjectives/modifier words to add to the available corpus of words for name generation or just come up with some and store them in somewhere

**Comment by aieshajohnson** [comment]
- https://grammar.yourdictionary.com/parts-of-speech/adjectives/list-of-adjective-words.html
- https://www.paperrater.com/page/lists-of-adjectives
- https://eslgrammar.org/list-of-adjectives/
- https://magoosh.com/english-speaking/positive-adjectives-the-ultimate-list/
- https://www.vocabulary.com/lists/238935
